### ISSUE TITLE
How can I compile and run rocHPCG on NVIDA cards?

### ISSUE THREAD

**Issue by han-minhee** [ROCmSoftwarePlatform/rocHPCG#21]
My current system has only NVIDA card installed,
I installed rocm-3.3.0 because of [the issue](https://github.com/ROCm-Developer-Tools/HIP/issues/2117) with rocm-3.5.0, and modified _/hipconfig_ to use nvcc.
CUDA 11.0

1.
It first yielded `nvcc fatal   : Unknown option '-Wno-unused-command-line-argument'`
error when _install.sh_ was run.
So I appended `-forward-unknown-to-host-compiler`, and the error was gone.

2.
It then yielded `gcc: error: unrecognized command line option ‘--amdgpu-target=gfx900’`
error,
so I commented below lines from _CMakeLists.txt_
```
foreach(target ${AMDGPU_TARGETS})
  list(APPEND HIP_HIPCC_FLAGS "--amdgpu-target=${target}")
endforeach()

```

3. 
but now I face this error:
```
error: identifier "__builtin_nontemporal_load" is undefined
```

Any kind of help will be appreciated.
Thanks in advance!

**Comment by ntrost57** [comment]
rocHPCG is developed for AMD hardware, you cannot use it on NVIDIA cards.
