### ISSUE TITLE
Is it possible to have mtx files of the generated matrix A?

### ISSUE THREAD

**Issue by paolodalberto** [ROCmSoftwarePlatform/rocHPCG#24]
I think for you guys should be easy to write into a portable format like COO mtx file the matrix generated during the GenerateProblem. What do you think ?

The idea behind is to find suitable sparse matrices that could be used as benchmark also for rocALUTION (for example). 

thank you

**Comment by ntrost57** [comment]
Currently, we have no plans to add matrix i/o.
