### ISSUE TITLE
Why the rocHPCG report is different from official HPCG ？

### ISSUE THREAD

**Issue by lilux618** [ROCmSoftwarePlatform/rocHPCG#44]
with nx ny nz = 580 280 280, the number of nonzero in rocHPCG is "Linear System Information::Number of Nonzero Terms=1201373839" while ,according to HPCG benchmark doc in https://hpcg-benchmark.org//  ,the No.Nonzero should be =8*8+ 12*4*(nx-2+ny-2+nz-2)+18*2*((nx-2)*(ny-2)+(nz-2)*(nx-2)+(ny-2)*(nz-2))+27*(nx-2)*(ny-2)*(nz-2), is 1178365432, what happened in rocHPCG, I am very
 puzzled

**Comment by ntrost57** [comment]
`88+ 124*(nx-2+ny-2+nz-2)+182((nx-2)(ny-2)+(nz-2)(nx-2)+(ny-2)(nz-2))+27(nx-2)(ny-2)(nz-2)` results to 1278789472 for 580 280 280
Where did you take those numbers? There might be some (boundary) zeros stored within the matrix, that do not contribute to the linear system but show up in matrix statistics.

**Comment by lilux618** [comment]
Sorry, the input is wrong due to markdown. The formula should be: 
```
No.Nonzero=8*8+`` 12*4*(nx-2+ny-2+nz-2)+18*2*((nx-2)*(ny-2)+(nz-2)*(nx-2)+(ny-2)*(nz-2))+27*(nx-2)*(ny-2)*(nz-2)
```
with 560 280 280 results to 1178365432 , which is the same with the results from official hpcg program，without considering the 0 boundary and I notice that the results get from rocHPCG report is different , while different nx ny nz results different nonzero number in rochpcg:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/李路/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/李路/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



nx | 16 | 16 | 16 | 16 | 16 | 16 | 16 | 24 | 24 | 24 | 24 | 24 | 96 | 560
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ny | 16 | 16 | 16 | 16 | 16 | 16 | 24 | 16 | 16 | 24 | 24 | 24 | 96 | 280
nz | 16 | 32 | 40 | 56 | 64 | 72 | 32 | 32 | 16 | 16 | 40 | 24 | 96 | 280
num | 4096 | 8192 | 10240 | 14336 | 16384 | 18432 | 12288 | 12288 | 6144 | 9216 | 23040 | 13824 | 884736 | 43904000
nonzero | 97336 | 198904 | 249688 | 351256 | 402040 | 452824 | 302680 | 302680 | 148120 | 225400 | 578200 | 343000 | 23393656 | 1178365432
rocm | 97336 | 230644 | 281428 | 382996 | 433780 | 484564 | 334420 | 334150 | 179590 | 258970 | 611770 | 376570 | 23859088 | 1201373839



</body>

</html>

**Comment by ntrost57** [comment]
HPCG uses some custom format to store the matrix (and does not store any zeros).
rocHPCG, however, uses ELLpack (which pads additional zeros) and permutes the matrix. Due to the permutation, additional zeros are filled into the ELL format.
You can verify that the matrices are identical, if you store the ELL matrix without the zeros.
