### ISSUE TITLE
About building rocHPCG without the root privilege

### ISSUE THREAD

**Issue by xwentian2020** [ROCmSoftwarePlatform/rocHPCG#45]
Hi, 

I am doing some benchmarking tests on AMD Instinct MI100 to test its performance in sparse matrix and vector multiplication, and find rocHPCG for benchmarking. I wonder if there are any suggestions to build the source code without the root privilege, after founding that the process of building looked complicated in some failed trials.

Thanks

**Comment by ntrost57** [comment]
You can build without root using e.g. cmake
```
cd rocHPCG && mkdir build && cd build  
cmake .. -DROCM_PATH=<rocmpath> -DAMDGPU_TARGETS=gfx908 -DHPCG_MPI=OFF  
make -j
```
Your binary will then be located in `rocHPCG/build/bin/`

**Comment by xwentian2020** [comment]
Hi, 

Is ROCm-4.5.2 suitable to be used in building rocHPCG on AMD MI100?
