### ISSUE TITLE
Why does the rochpcg result show that the data transportation capacity is higher than the bandwidth?

### ISSUE THREAD

**Issue by lilux618** [ROCmSoftwarePlatform/rocHPCG#46]
I ran rochpcg program with 560 280 280 60 parameters, and the results are as follows:
```
GB/s Summary=
GB/s Summary::Raw Read B/W=1208.45
GB/s Summary::Raw Write B/W=279.154
GB/s Summary::Raw Total B/W=1487.6
GB/s Summary::Total with convergence and optimization phase overhead=1476.61
GFLOP/s Summary=
GFLOP/s Summary::Raw DDOT=180.169
GFLOP/s Summary::Raw WAXPBY=76.0718
GFLOP/s Summary::Raw SpMV=158.515
GFLOP/s Summary::Raw MG=212.227 
GFLOP/s Summary::Raw Total=196.268
```
However I notice that the bandwidth of MI100 is up to 1.2TB/s according the instinct-mi100-brochure.pdf, why the GB/s of rochpcg is nearly 1.5TB/s which can be  higher than the bandwidth 1.2TB/s ?

**Comment by ntrost57** [comment]
Those numbers are computed by the HPCG benchmark. They are corresponding to the standard implementation which differs from rocHPCG and therefore the numbers are not reflecting the actual bandwidth of the GPU.
We cannot modify or adjust those numbers, as they are part of the reference code.
