### ISSUE TITLE
About an issue happened in building the code in the dev branch

### ISSUE THREAD

**Issue by xwentian2020** [ROCmSoftwarePlatform/rocHPCG#49]
Hi,

In building the latest version of rocHPCG on AMD MI210, there happened an issue about  no definition of a local variable i in the main.c. The code snippet of the while loop after the line 482. 

/nfs/site/home/xuwentia/Documents/rocHPCG/src/YAML_Doc.cpp: In member function ���std::string YAML_Doc::generateYAML()���:
/nfs/site/home/xuwentia/Documents/rocHPCG/src/YAML_Doc.cpp:73:11: warning: ignoring return value of ���int system(const char*)���, declared with attribute warn_unused_result [-Wunused-result]
   73 |     system(mkdir_cmd.c_str());
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~
/nfs/site/home/xuwentia/Documents/rocHPCG/src/YAML_Doc.cpp:62:29: warning: ���%02d��� directive writing between 2 and 11 bytes into a region of size between 1 and 17 [-Wformat-overflow=]
   62 |   sprintf (sdate,"%04d.%02d.%02d.%02d.%02d.%02d",ptm->tm_year + 1900, ptm->tm_mon+1,
      |                             ^~~~
In file included from /usr/include/stdio.h:867,
                 from /usr/include/c++/9/cstdio:42,
                 from /usr/include/c++/9/ext/string_conversions.h:43,
                 from /usr/include/c++/9/bits/basic_string.h:6496,
                 from /usr/include/c++/9/string:55,
                 from /usr/include/c++/9/bits/locale_classes.h:40,
                 from /usr/include/c++/9/bits/ios_base.h:41,
                 from /usr/include/c++/9/ios:42,
                 from /usr/include/c++/9/ostream:38,
                 from /usr/include/c++/9/iostream:39,
                 from /nfs/site/home/xuwentia/Documents/rocHPCG/src/YAML_Doc.cpp:17:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:34: note: ���__builtin___sprintf_chk��� output between 20 and 72 bytes into a destination of size 25
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/nfs/site/home/xuwentia/Documents/rocHPCG/src/main.cpp: In function ���int main(int, char**)���:
/nfs/site/home/xuwentia/Documents/rocHPCG/src/main.cpp:487:43: error: ���i��� was not declared in this scope
  487 |     if (rank==0) HPCG_fout << "Call [" << i << "] Scaled Residual [" << normr/normr0 << "]" << endl;
      |                                           ^
/nfs/site/home/xuwentia/Documents/rocHPCG/src/main.cpp:489:21: error: ���i��� was not declared in this scope
  489 |     if(rank == 0 && i < numberOfCgSets)
      |                     ^
/nfs/site/home/xuwentia/Documents/rocHPCG/src/main.cpp:504:27: error: ���i��� was not declared in this scope
  504 |     testnorms_data.values[i] = normr/normr0; // Record scaled residual from this run
      |                           ^
/nfs/site/home/xuwentia/Documents/rocHPCG/src/OutputFile.cpp: In member function ���std::string OutputFile::generate()���:
/nfs/site/home/xuwentia/Documents/rocHPCG/src/OutputFile.cpp:118:29: warning: ���%02d��� directive writing between 2 and 11 bytes into a region of size between 1 and 17 [-Wformat-overflow=]
  118 |   sprintf (sdate,"%04d-%02d-%02d_%02d-%02d-%02d",ptm->tm_year + 1900, ptm->tm_mon+1,
      |                             ^~~~
In file included from /usr/include/stdio.h:867,
                 from /usr/include/c++/9/cstdio:42,
                 from /usr/include/c++/9/ext/string_conversions.h:43,
                 from /usr/include/c++/9/bits/basic_string.h:6496,
                 from /usr/include/c++/9/string:55,
                 from /usr/include/c++/9/bits/locale_classes.h:40,
                 from /usr/include/c++/9/bits/ios_base.h:41,
                 from /usr/include/c++/9/ios:42,
                 from /usr/include/c++/9/istream:38,
                 from /usr/include/c++/9/fstream:38,
                 from /nfs/site/home/xuwentia/Documents/rocHPCG/src/OutputFile.cpp:16:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:34: note: ���__builtin___sprintf_chk��� output between 20 and 72 bytes into a destination of size 25
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/rochpcg.dir/build.make:532: src/CMakeFiles/rochpcg.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:94: src/CMakeFiles/rochpcg.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by ntrost57** [comment]
Should be solved in the latest version.
Please always use master branch for production.
