### ISSUE TITLE
Make printing of "Using HIP device" message opt-in?

### ISSUE THREAD

**Issue by pbauman** [ROCmSoftwarePlatform/rocHPCG#52]
https://github.com/ROCmSoftwarePlatform/rocHPCG/blob/6a2097fecabdaf26df6ecd5c86c11c14049162bf/src/main.cpp#L134

For very large scale runs, this can generate megabytes of output. Perhaps make it opt-in to print this message (maybe only in debug mode)? That would help trim logging of large scale benchmark runs.

**Comment by ntrost57** [comment]
Change such that only master rank will print device infos.
