### ISSUE TITLE
instruction for executing with GPU?

### ISSUE THREAD

**Issue by du00d** [ROCmSoftwarePlatform/rocHPCG#54]
Hi, 
Is it possible to add the instructions for executing the compiled binary with MI210 GPUs? I cannot seem to run the program with MI210 GPUs, or should it be automatic?

Thanks in advance.

**Comment by ntrost57** [comment]
If you have compiled on a MI210 system, it should work out of the box.

**Comment by du00d** [comment]
Thanks, and if I would like to use multiple HIP devices, does that need to be specified? I believe it's supposed to detect all devices connected to the system?

**Comment by ntrost57** [comment]
You need to use OpenMPI in that case.

**Comment by du00d** [comment]
Closing the issue, it's resolved. Thanks!
