### ISSUE TITLE
Missing cmath/libcxx

### ISSUE THREAD

**Issue by zilverberg** [ROCmSoftwarePlatform/rocHPCG#56]
On Ubuntu 22.04.1 LTS the compilation fails due to missing cmath.
Installing libstdc++-12-dev fixes this.

credits to @elbriggs in https://github.com/RadeonOpenCompute/ROCm/issues/1843

```
In file included from <built-in>:1:
/opt/rocm-5.4.0/llvm/lib/clang/15.0.0/include/__clang_hip_runtime_wrapper.h:50:10: fatal error: 'cmath' file not found
#include <cmath>
         ^~~~~~~

```

**Comment by ntrost57** [comment]
Closing this, as it is not related to rocHPCG.

**Comment by ggorman** [comment]
You can fix it by installing libstdc++ (e.g. `sudo apt install g++-12`).
